# Trunk configuration file for building and serving the terminal emulator
# Trunk is a WASM web application bundler for Rust

[build]
# Target directory for build outputs
target = "index.html"
public_url = "/zzhack"
# Directory to output the built files
dist = "dist"
# Enable optimization for release builds
release = false

# Copy data directory to dist for file serving
[[copy-dir]]
source = "data"
target = "data"

[watch]
# Watch for changes in these directories
watch = ["src", "input.css", "tailwind.config.js"]
# Ignore these patterns when watching for changes
ignore = ["dist", "target"]

[serve]
# Port for the development server
port = 8080
# Open browser automatically when starting the server
open = true

[clean]
# Clean configuration for trunk clean command
cargo = true
