# Trunk configuration file for building and serving the terminal emulator
# Trunk is a WASM web application bundler for Rust

[build]
# Target directory for build outputs
target = "index.html"
public_url = "/"
# Directory to output the built files
dist = "dist"
# Enable optimization for release builds
release = false

# Copy data directory to dist for file serving
[[copy-dir]]
source = "data"
target = "data"

[serve]
# Port for the development server
port = 8080
# Open browser automatically when starting the server
open = true

[clean]
# Clean configuration for trunk clean command
cargo = true
