[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
site_config = { path = "../site_config" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite = { version = "0.31.0", features = ["bundled"] }
